# Generated by Django 4.2.3 on 2025-04-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('societe', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_identification_fiscale', models.CharField(blank=True, max_length=50, null=True)),
                ('registre_commerce', models.CharField(blank=True, max_length=50, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
